{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hypermedea",
    "module": "mqtt-binding",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mqtt-binding-0.4.1.jar",
          "url": "mqtt-binding-0.4.1.jar",
          "size": 9060,
          "sha512": "5d211fe1e2877aad404e1918a8b98a0fc96495891b61904ebfc1cd877e5347e20850c5c39df786627518fa9b083597c060661a855b9bc772a644334ba4fcb0f1",
          "sha256": "64513faed044535b5c9a8cbcf690cfbfadf530b904aeb3e3e3fd7ae63d4be6da",
          "sha1": "13c6140f10756a2608813903ce49ec7040d7ea2b",
          "md5": "0dcbdcb53daf2be23b6549c0811c17a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.mqttv5.client",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "mqtt-binding-0.4.1.jar",
          "url": "mqtt-binding-0.4.1.jar",
          "size": 9060,
          "sha512": "5d211fe1e2877aad404e1918a8b98a0fc96495891b61904ebfc1cd877e5347e20850c5c39df786627518fa9b083597c060661a855b9bc772a644334ba4fcb0f1",
          "sha256": "64513faed044535b5c9a8cbcf690cfbfadf530b904aeb3e3e3fd7ae63d4be6da",
          "sha1": "13c6140f10756a2608813903ce49ec7040d7ea2b",
          "md5": "0dcbdcb53daf2be23b6549c0811c17a6"
        }
      ]
    }
  ]
}
