{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hypermedea",
    "module": "mqtt-binding",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mqtt-binding-0.4.1.jar",
          "url": "mqtt-binding-0.4.1.jar",
          "size": 9060,
          "sha512": "872df87538eb2080f117af4200c9d05b4ab74a674e180574fdc29a192840d8f3019130a20b09164c09f6dd045386bc0089d9aac9311bb3cd0497220fd899b914",
          "sha256": "89b1e7d369aa5ba65ab3d0f78327b3f63ced638da832e0a0bc6c8800e8382d4c",
          "sha1": "748e969546373f3bc6db952f2a4af6d1e0339ed6",
          "md5": "1ee8053d671bd4e64ab470aa6dcc11ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.mqttv5.client",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "mqtt-binding-0.4.1.jar",
          "url": "mqtt-binding-0.4.1.jar",
          "size": 9060,
          "sha512": "872df87538eb2080f117af4200c9d05b4ab74a674e180574fdc29a192840d8f3019130a20b09164c09f6dd045386bc0089d9aac9311bb3cd0497220fd899b914",
          "sha256": "89b1e7d369aa5ba65ab3d0f78327b3f63ced638da832e0a0bc6c8800e8382d4c",
          "sha1": "748e969546373f3bc6db952f2a4af6d1e0339ed6",
          "md5": "1ee8053d671bd4e64ab470aa6dcc11ed"
        }
      ]
    }
  ]
}
