{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hypermedea",
    "module": "opcua-binding",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opcua-binding-0.4.2.jar",
          "url": "opcua-binding-0.4.2.jar",
          "size": 13703,
          "sha512": "ca14ac47ba4b71e4742a56e9161fd3c352e38f5b2c467c1f1f3553a29a60eaddcd8366d2a439917cd36b60150fd990d9eb404df58d03fa34a344f0e8decaab5d",
          "sha256": "1c1876ef45117ccce3d6f2a7e2395986cd590a6d7da6db03edffa9f7176e1fa9",
          "sha1": "ba1b24ac957487962a21f03c30afa1c3e18e4121",
          "md5": "3cfc678701b11fcf9d824da0c308b340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.milo",
          "module": "sdk-client",
          "version": {
            "requires": "0.6.8"
          }
        },
        {
          "group": "org.apache.jena",
          "module": "jena-core",
          "version": {
            "requires": "3.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "opcua-binding-0.4.2.jar",
          "url": "opcua-binding-0.4.2.jar",
          "size": 13703,
          "sha512": "ca14ac47ba4b71e4742a56e9161fd3c352e38f5b2c467c1f1f3553a29a60eaddcd8366d2a439917cd36b60150fd990d9eb404df58d03fa34a344f0e8decaab5d",
          "sha256": "1c1876ef45117ccce3d6f2a7e2395986cd590a6d7da6db03edffa9f7176e1fa9",
          "sha1": "ba1b24ac957487962a21f03c30afa1c3e18e4121",
          "md5": "3cfc678701b11fcf9d824da0c308b340"
        }
      ]
    }
  ]
}
