{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hypermedea",
    "module": "ros2-binding",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ros2-binding-0.4.2.jar",
          "url": "ros2-binding-0.4.2.jar",
          "size": 19182,
          "sha512": "6adbdbb7b33bcb64790e858484a0174b80046a43b64725ae0b18a63293965c3861190ce74228e62d3901f78173bb2d1acf5d4da712bd75b3dd5f645dc3fb0e48",
          "sha256": "06f49eaa2d26982c60c5fae2713432ccade5438537df4dde19a284a81d3af15c",
          "sha1": "1ea96dfca9241e7681a5743fc023693014025326",
          "md5": "bfa05931fa64083f9fda922384eaaf10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ros2-binding-0.4.2.jar",
          "url": "ros2-binding-0.4.2.jar",
          "size": 19182,
          "sha512": "6adbdbb7b33bcb64790e858484a0174b80046a43b64725ae0b18a63293965c3861190ce74228e62d3901f78173bb2d1acf5d4da712bd75b3dd5f645dc3fb0e48",
          "sha256": "06f49eaa2d26982c60c5fae2713432ccade5438537df4dde19a284a81d3af15c",
          "sha1": "1ea96dfca9241e7681a5743fc023693014025326",
          "md5": "bfa05931fa64083f9fda922384eaaf10"
        }
      ]
    }
  ]
}
