{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hypermedea",
    "module": "hypermedea",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hypermedea-0.4.2.jar",
          "url": "hypermedea-0.4.2.jar",
          "size": 107918,
          "sha512": "46317d7ad745b993b2111cfd1f46d55573041ba7769f0afb8797ad5612cc06ad063d064ce8cdf0a900b4dcb20849356d2d59cbbca85430a1e2df13db4ec67e89",
          "sha256": "22866e031bcf2cc7f0fdfa6f2b25853f600138cdb7daa65cac0c235191f490f5",
          "sha1": "a68687770cde6331f45dd082be0b455a6910959d",
          "md5": "dcc905b2ea779d7a4e35d03c810fce3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.jena",
          "module": "jena-core",
          "version": {
            "requires": "3.16.0"
          }
        },
        {
          "group": "org.apache.jena",
          "module": "jena-arq",
          "version": {
            "requires": "3.16.0"
          }
        },
        {
          "group": "org.apache.jena",
          "module": "jena-iri",
          "version": {
            "requires": "3.16.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "hypermedea-0.4.2.jar",
          "url": "hypermedea-0.4.2.jar",
          "size": 107918,
          "sha512": "46317d7ad745b993b2111cfd1f46d55573041ba7769f0afb8797ad5612cc06ad063d064ce8cdf0a900b4dcb20849356d2d59cbbca85430a1e2df13db4ec67e89",
          "sha256": "22866e031bcf2cc7f0fdfa6f2b25853f600138cdb7daa65cac0c235191f490f5",
          "sha1": "a68687770cde6331f45dd082be0b455a6910959d",
          "md5": "dcc905b2ea779d7a4e35d03c810fce3e"
        }
      ]
    }
  ]
}
