{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hypermedea",
    "module": "ros-binding",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ros-binding-0.4.1.jar",
          "url": "ros-binding-0.4.1.jar",
          "size": 21459,
          "sha512": "f6ca4074c287bc71a00caf3cac87fa08ab1d06afbdbaf04d8ef271723a01a2c531f04c016958e5f93fad48fe40dbad3420325cb1ab464d54b750c0ee91cc875c",
          "sha256": "b01a9c1d5fd70833b0caac199982bf299d3dfe19d935d43cd05c45f261ab8692",
          "sha1": "0f71725f3b42163f41617dcd9d69903308c0a7f5",
          "md5": "af7cbc8d3e4720be9e339360454dbf40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-client",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-container-grizzly-client",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "org.glassfish.tyrus",
          "module": "tyrus-server",
          "version": {
            "requires": "1.17"
          }
        }
      ],
      "files": [
        {
          "name": "ros-binding-0.4.1.jar",
          "url": "ros-binding-0.4.1.jar",
          "size": 21459,
          "sha512": "f6ca4074c287bc71a00caf3cac87fa08ab1d06afbdbaf04d8ef271723a01a2c531f04c016958e5f93fad48fe40dbad3420325cb1ab464d54b750c0ee91cc875c",
          "sha256": "b01a9c1d5fd70833b0caac199982bf299d3dfe19d935d43cd05c45f261ab8692",
          "sha1": "0f71725f3b42163f41617dcd9d69903308c0a7f5",
          "md5": "af7cbc8d3e4720be9e339360454dbf40"
        }
      ]
    }
  ]
}
